name: Conversion et Copie

on:
  push:
    branches:
      - main

jobs:
  convert_and_copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Générer la Version
      run: echo "1.0" > $GITHUB_WORKSPACE/version.txt  # Remplacez "1.0" par la version de votre projet

    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Pandoc
      run: sudo apt-get install pandoc

    - name: Installer pdflatex
      run: sudo apt-get install texlive-xetex
    
    - name: Générer le fichier version.txt
      run: echo $(git rev-parse HEAD) > version.txt

    - name: creation du dossier pedagogique
      run: mkdir -p kit_pedagogique  # Créez le dossier de destination s'il n'existe pas

    - name: Generate HTML page
      run: |
        echo "<html>" > index.html
        echo "<head><title>PDF Files</title></head>" >> index.html
        echo "<body>" >> index.html
        commit_date=$(git show -s --format=%ci)
        echo "<h1>Commit date: $commit_date</h1>" >> index.html
        echo "<h1>List of PDF Files</h1>" >> index.html
        
        # for file in *.pdf
        # do
        #   echo "<a href=\"$file\">$file</a><br>" >> index.html
        # done
        # echo "<div id='readme-content'></div>" >> index.html
        # // add the content of readme.md to the index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/markdown-it/8.4.2/markdown-it.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/go.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/python.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/javascript.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/c.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/cpp.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/bash.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/ini.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/json.min.js'></script>" >> index.html
        # echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/xml.min.js'></script>" >> index.html

        # echo "<script>" >> index.html
        # echo "fetch('README.md')" >> index.html
        # echo "  .then(response => response.text())" >> index.html
        # echo "  .then(text => {" >> index.html
        # echo "    const md = window.markdownit();" >> index.html
        # echo "    const result = md.render(text);" >> index.html
        # echo "    document.getElementById('readme-content').innerHTML = result;" >> index.html
        # echo "    document.querySelectorAll('pre code').forEach((block) => {" >> index.html
        # echo "      hljs.highlightBlock(block);" >> index.html
        # echo "    });" >> index.html
        # echo "  });" >> index.html
        # echo "</script>" >> index.html

        echo "</body>" >> index.html
        echo "</html>" >> index.html

        cp index.html kit_pedagogique/index.html

    - name: Conversion en PDF
      run: |
        

        for file in content/*.md; do
          # Récupérez le nom du fichier sans l'extension .md
          filename=$(basename "$file" .md)
          
          # Convertissez le fichier Markdown en PDF
          pandoc "$file" --template=template/latex_template.tex --pdf-engine=xelatex -o "kit_pedagogique/${filename}.pdf" --pdf-engine-opt=-shell-escape --include-in-header=template/minted-setup.tex

        done


    - name: Copier le Code Eleve
      run: |
        mkdir -p kit_pedagogique/code  # Créez le dossier de destination s'il n'existe pas
        mkdir -p kit_pedagogique/ressources  # Créez le dossier de destination s'il n'existe pas
        
        # Copiez l'intégralité du dossier eleve dans le dossier code du kit pédagogique
        cp -r code/student/* kit_pedagogique/code/
        cp -r ressources/student/* kit_pedagogique/ressources/


    - name: Deploy on gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./kit_pedagogique
        force_orphan: true