name: Conversion et Copie

on:
  push:
    branches:
      - main

jobs:
  convert_and_copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Générer la Version
      run: echo "1.0" > $GITHUB_WORKSPACE/version.txt  # Remplacez "1.0" par la version de votre projet

    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Pandoc
      run: sudo apt-get install pandoc

    - name: Installer pdflatex
      run: sudo apt-get install texlive-xetex
    
    - name: Générer le fichier version.txt
      run: echo $(git rev-parse HEAD) > version.txt

    - name: Generate HTML page
      run: |
        echo "<html>" > index.html
        echo "<head><title>PDF Files</title></head>" >> index.html
        echo "<body>" >> index.html
        commit_date=$(git show -s --format=%ci)
        echo "<h1>Commit date: $commit_date</h1>" >> index.html
        echo "<h1>List of PDF Files</h1>" >> index.html
        
        for file in *.pdf
        do
          echo "<a href=\"$file\">$file</a><br>" >> index.html
        done
        echo "</body>" >> index.html
        echo "</html>" >> index.html

        cp index.html kit_pedagogique/index.html

    - name: Conversion en PDF
      run: |
        mkdir -p kit_pedagogique  # Créez le dossier de destination s'il n'existe pas

        for file in content/*.md; do
          # Récupérez le nom du fichier sans l'extension .md
          filename=$(basename "$file" .md)
          
          # Convertissez le fichier Markdown en PDF
          pandoc "$file" --template=template/latex_template.tex --pdf-engine=xelatex -o "kit_pedagogique/${filename}.pdf" 

        done


    - name: Copier le Code Eleve
      run: |
        mkdir -p kit_pedagogique/code  # Créez le dossier de destination s'il n'existe pas
        mkdir -p kit_pedagogique/ressources  # Créez le dossier de destination s'il n'existe pas
        
        # Copiez l'intégralité du dossier eleve dans le dossier code du kit pédagogique
        cp -r code/student/* kit_pedagogique/code/
        cp -r ressources/student/* kit_pedagogique/ressources/


    - name: Deploy on gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./kit_pedagogique
        force_orphan: true